### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by tonedwtf** [henkelmax/view-distance-fix#2]
**Bug description**
I have it installed on my 1.19.3 Fabric server and it is not working.

**Steps to reproduce the issue**
1. Install the viewdistancefix 1.19.3-1.0.0 mod.
2. Go into the server.
3. Change view distance.
4. Nothing happens, it still uses the server's set view distance.

**Log files**
[Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).](https://gist.github.com/Uzae/e0e2aba2b5f7083781d63c6771805e5b)

**Versions**
fabric_1.19.3.jar (Fabric Version)
Minecraft 1.19.3

**Other mods**
fabric-api-0.71.0+1.19.3.jar
fabric-language-kotlin-1.9.0+kotlin.1.8.0.jar
FabricTPA-3.2.1.jar
homabric-2.0.2+1.19.x.jar
InvView-1.4.10-1.19.3+.jar
ledger-1.2.6.jar
lithium-fabric-mc1.19.3-0.10.4.jar
MCDiscordChat-1.19.3-2.1.2.jar
phosphor-fabric-mc1.19.x-0.8.1.jar
servux-fabric-1.19.0-0.1.0.jar
spark-1.10.26-fabric.jar
vanish-1.3.1.jar

**Comment by henkelmax** [comment]
The mod does **NOT** change the view distance. Read the mod description.

**Comment by tonedwtf** [comment]
Maybe I worded it wrong, but the server is not tricking the client into thinking that it has the same render distance as the client. Myself and others are not getting the results shown in xisumavoid's video at: 7:13, https://youtu.be/8k23giaWP64

**Comment by henkelmax** [comment]
What render distance is your server set to and whats the distance on your client?

**Comment by globalista-dev** [comment]
Can also confirm this is a problem. Server's render distance is set to 10, client's render distance is set to 32. You should reopen this issue to further investigate. Since I'm not sure what is happening, I also don't know what other info I need to provide. 

EDIT: uploaded to imgur visual proof that it isn't working for me: [https://imgur.com/DUsYc5x](https://imgur.com/DUsYc5x)

**Comment by DitIsHaider** [comment]
I have the exact same problem.
I'm on 1.19.3
