### ISSUE TITLE
1.20.2 player login issue with mod installed

### ISSUE THREAD

**Issue by sakura-ryoko** [henkelmax/view-distance-fix#4]
**Bug description**
When installing view distance fix on a fabric 1.20.2 server, it blocks players from logging into the server.

**Steps to reproduce the issue**
1 - Install a Minecraft 1.20.2 fabric-based server.
2 - Insall Fabric API
3 - Install ViewDistanceFix
4 - Launch Server
5 - Attempt to login using client.

**Expected behavior**
The MOD allows players to login when installed.

**Log files**
[3ba8b7d1180fdad85c8a8f6b9a982d87-5f92503bd19bdc2b058177165c5de348ac955e45.zip](https://github.com/henkelmax/view-distance-fix/files/12743168/3ba8b7d1180fdad85c8a8f6b9a982d87-5f92503bd19bdc2b058177165c5de348ac955e45.zip)

**Versions**
- Minecraft version 1.20.2
- Fabric loader version 0.14.22
- Mod version 1.0.0

**Other mods**
<None>

**Screenshots (Optional)**
<None>

**Comment by henkelmax** [comment]
Please post the full logs with GitHub gist, like described in the template.

**Comment by sakura-ryoko** [comment]
> Please post the full logs with GitHub gist, like described in the template.

Better ?
